### ISSUE TITLE
Rice Dupe with scythe 

### ISSUE THREAD

**Issue by Bookcrafter** [Anxietie/Farmers-Addons#3] opened 2024-12-23 03:00 UTC
There is a problem with the Scythe when trrying to harvest rice. It does not break the block and lets you get an infinite amount of rice. I am using version 2.2 of Farmers Addons and version 1.20.1-2.2.4=Refabricated of Farmer's Delight.

**Comment by Anxietie** [comment] 2024-12-27 19:55
this is a quirk with how farmers delight harvests rice. ill see what i can do

**Comment by Anxietie** [comment] 2024-12-27 22:37
with the way farmers delight harvests rice specifically, harvesting with a scythe wont function the same as simply destroying the block as was intended by the creator of farmers delight. the difference is the rice on top will start from age 0 and grow to max age whereas if you destroyed the block normally it would have to regrow completely. so its 1 age difference essentially. if this is okay with you then the bug is fixed with the next update.

**Closed as completed by Anxietie** 2024-12-27 22:37 UTC
Labels: bug
